on:
  push:
  pull_request:
  schedule:
  - cron: "0 0 4 * *"

name: Check spelling

jobs:
  check_spelling:

    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2

      - name: Install aspell
        run: sudo apt-get install aspell

      - name: Run spell check 
        run: ./do_spell_check.sh

      - name: Run spell check from Docker
        run: ./do_spell_check_docker.sh
